#!/bin/bash
# intero — User configuration
# Copy to config.sh and customize

# Bar style: parallelogram | blocks | dots | geometric | squares
INTERO_BAR_STYLE="parallelogram"

# Context thresholds (percentage)
# INTERO_CTX_WARN=50
# INTERO_CTX_CAUTION=70
# INTERO_CTX_CRITICAL=85

# Burn rate thresholds (tokens/min)
# INTERO_BURN_WARN=2000
# INTERO_BURN_CRITICAL=5000

# Fetch staleness thresholds (seconds)
# INTERO_FETCH_WARN=3600      # 1 hour
# INTERO_FETCH_CRITICAL=86400  # 1 day

# Feature toggles (1 = on, 0 = off)
# INTERO_SHOW_PR=1
# INTERO_SHOW_PEAK=1
# INTERO_SHOW_CACHE=1
# INTERO_SHOW_BURN=1
# INTERO_SHOW_WEIGHTED=1
# INTERO_STATUS_TTL=120
# INTERO_STATUS_QUIET=0

# ── Tab title (hooks/tab-summary.py + hooks/session-title.py) ─────────────────
# Title = ~/path · branch · summary. The summary is generated by a detached
# curl→Anthropic API call (haiku-class model). Requires ANTHROPIC_API_KEY.
# Model resolved by lib/model.sh from ~/.cache/intero/summary-model (seeded
# by install.sh). Needs CLAUDE_CODE_DISABLE_TERMINAL_TITLE=1.
# INTERO_TAB_DISABLE_SUMMARY=0   # 1 = "~/path · branch" only, never call API
# INTERO_TAB_MODEL=              # pin a model id; empty = use lib/model.sh
# INTERO_TAB_COOLDOWN=90         # seconds between summary refreshes
# INTERO_TAB_TIMEOUT=8           # max seconds for the curl call
# INTERO_TAB_MODEL_MATRIX=       # path to ops routing YAML (future, leave unset)

# ── Layout ──────────────────────────────────────────────────────────────────
# Each line is an array of section names. Sections render left-to-right
# with │ separators. Reorder, move between lines, or remove to customize.
# Empty/missing sections are silently skipped.
#
# Available sections:
#   model dir worktree lines branch sync pr duration peak status
#   context burn cache
#   rate5h rate7d

INTERO_LINE1="model dir lines branch sync pr"
INTERO_LINE2="context tokens burn cache duration peak status"
INTERO_LINE3="rate5h"
INTERO_LINE4="rate7d"
